//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuikMeds
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerComment
    {
        public int CommentId { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public System.DateTime ThisDateTime { get; set; }
        public int PID { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
